## Pivot Tables

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
'Date': pd.date_range('2023-01-01', periods=20),
'Product': ['A', 'B', 'C', 'D'] * 5,
'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
'Sales': np. random. randint(100, 1000, 20),
'Units': np. random. randint (10, 100, 20),
'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [3]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    793     86   John  January      Q1
1  2023-01-02       B   West    492     69   Mary  January      Q1
2  2023-01-03       C  North    514     28    Bob  January      Q1
3  2023-01-04       D  South    870     39  Alice  January      Q1
4  2023-01-05       A   East    302     47   John  January      Q1
5  2023-01-06       B   West    663     30   Mary  January      Q1
6  2023-01-07       C  North    754     35    Bob  January      Q1
7  2023-01-08       D  South    737     63  Alice  January      Q1
8  2023-01-09       A   East    211     20   John  January      Q1
9  2023-01-10       B   West    203     15   Mary  January      Q1
10 2023-01-11       C  North    676     54    Bob  January      Q1
11 2023-01-12       D  South    928     34  Alice  January      Q1
12 2023-01-13       A   East    541     98   John  January      Q1
13 2023-01-14       B   West    508     61   Mary  January      Q1
14 2023-01-15       C  North    247     85    Bob  January      Q1
15 2023-01-16       D  South    955     13  Alice  January      Q1
16 2023-01-17       A   East    778     20   John  January      Q1
17 2023-01-18       B   West    817     24   Mary  January      Q1
18 2023-01-19       C  North    820     96    Bob  January      Q1
19 2023-01-20       D  South    479     63  Alice  January      Q1

In [4]:
pd.pivot_table(df, values='Sales', index='Product', columns='Region', aggfunc='median', fill_value=0)

Region    East  North  South   West
Product
A        541.0    0.0    0.0    0.0
B          0.0    0.0    0.0  508.0
C          0.0  676.0    0.0    0.0
D          0.0    0.0  870.0    0.0

In [11]:
pd.crosstab(df['Product'], df['Region'], values=df['Sales'], aggfunc='sum',)

Region     East   North   South    West
Product
A        2625.0     NaN     NaN     NaN
B           NaN     NaN     NaN  2683.0
C           NaN  3011.0     NaN     NaN
D           NaN     NaN  3969.0     NaN